### ISSUE TITLE
Visualizar favoritos del usuario

### ISSUE THREAD

**Issue by alfpain** [cognits/frenzy#3]
Si eliminamos o agregamos un cliente como favorito, y queremos ingresar a favoritos para visualizar si ya el usuario lo tiene asignado, en la primera visualización no se muestran los cambios, es decir no aparece agregado o si fue eliminado el cliente,  si nos salimos e ingresamos de nuevo a tus favoritos ya muestra la información actualizada. El problema es que muestra la información hasta la segunda vez que ingresamos después de un cambio realizado.

**Comment by sebasibarguen** [comment]
se arreglo en el branch `dev`. Cada vez que abrimos una `View` o vista con AngularJS, este se encarga de llamar al respectivo `controller`. El el caso de usar "tabs", esto no siempre estaba pasando. O sea, a veces llamaba el controllador y a veces no. Lo unico que agregue fue a puro tuvo llame la funcion de jalar los favoritos cada vez que habra "Tus Favoritos"
