### ISSUE TITLE
Visualizar promociones salvadas del usuario

### ISSUE THREAD

**Issue by alfpain** [cognits/frenzy#4]
Si eliminamos o agregamos una promoción como favorito, y queremos ingresar a salvados para visualizar si ya el usuario la tiene asignada, en la primera visualización no se muestran los cambios, es decir no aparece agregada o si fue eliminada la promoción,  si nos salimos e ingresamos de nuevo a tus salvados ya muestra la información actualizada. El problema es que muestra la información hasta la segunda vez que ingresamos después de un cambio realizado.

**Comment by sebasibarguen** [comment]
Ya fue resuelto usando 
`$scope.$on('$ionicView.enter', function()`
