### ISSUE TITLE
funcion mensaje ios

### ISSUE THREAD

**Issue by jatamayo** [cognits/frenzy#6]
la funcion para enviar mensajes corre perfectamente en android, pero en ios en ocaciones abre el mensaje que se desea enviar en donde se coloca el numero telefonico y en ocaciones lo agrega correctamente.

**Comment by LudwinGarcia** [comment]
Es necesario poder verificar cuando la aplicación de IOS este creada como tal. Al igual que se creo el ```.apk``` para android.

**Comment by LudwinGarcia** [comment]
La función fue probada al convertir la aplicación para IOS y funciono correctamente.
