### ISSUE TITLE
icon heart popover

### ISSUE THREAD

**Issue by jatamayo** [cognits/frenzy#9]
al momento de utilizar la funcion back ya no funciona correctamente el color del icono del popoover, no se hace el refresh, se necesita actualizar la vista para que pinte el icono de corazon.

**Comment by LudwinGarcia** [comment]
Se arreglo usando el controller ```PaizCtrl``` agregando un ```$scope.$on ('$ionicView.enter', function() {});``` y se agrego una función ```$scope.heartPopver``` para cambiar color al corazón.
